// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project 1

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Panel7 = NULL;
// event funtions
void ui_event_Label19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel17 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel17, 480);
    lv_obj_set_height(ui_Panel17, 280);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -196);
    lv_obj_set_y(ui_Label19, -117);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "<<返回");
    lv_obj_add_flag(ui_Label19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_Label19, &ui_font_Font15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, -116);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "数据信息");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Font17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel7, 440);
    lv_obj_set_height(ui_Panel7, 215);
    lv_obj_set_x(ui_Panel7, 0);
    lv_obj_set_y(ui_Panel7, 14);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Label19, ui_event_Label19, LV_EVENT_ALL, NULL);

    // This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project 1

#include "../ui.h"

    lv_obj_t* ui_Screen2 = NULL;
    lv_obj_t* ui_Panel17 = NULL;
    lv_obj_t* ui_Label19 = NULL;
    lv_obj_t* ui_Label12 = NULL;
    lv_obj_t* ui_Panel7 = NULL;
    // event funtions
    void ui_event_Label19(lv_event_t * e)
    {
        lv_event_code_t event_code = lv_event_get_code(e);

        if (event_code == LV_EVENT_CLICKED) {
            _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        }
    }

    // build funtions

    void ui_Screen2_screen_init(void)
    {
        ui_Screen2 = lv_obj_create(NULL);
        lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

        ui_Panel17 = lv_obj_create(ui_Screen2);
        lv_obj_set_width(ui_Panel17, 480);
        lv_obj_set_height(ui_Panel17, 280);
        lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
        lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

        ui_Label19 = lv_label_create(ui_Screen2);
        lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
        lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
        lv_obj_set_x(ui_Label19, -196);
        lv_obj_set_y(ui_Label19, -117);
        lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
        lv_label_set_text(ui_Label19, "<<返回");
        lv_obj_add_flag(ui_Label19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
        lv_obj_set_style_text_font(ui_Label19, &ui_font_Font15, LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_Label12 = lv_label_create(ui_Screen2);
        lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
        lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
        lv_obj_set_x(ui_Label12, 0);
        lv_obj_set_y(ui_Label12, -116);
        lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
        lv_label_set_text(ui_Label12, "数据信息");
        lv_obj_set_style_text_font(ui_Label12, &ui_font_Font17, LV_PART_MAIN | LV_STATE_DEFAULT);

        ui_Panel7 = lv_obj_create(ui_Screen2);
        lv_obj_set_width(ui_Panel7, 440);
        lv_obj_set_height(ui_Panel7, 215);
        lv_obj_set_x(ui_Panel7, 0);
        lv_obj_set_y(ui_Panel7, 14);
        lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
        lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

        lv_obj_add_event_cb(ui_Label19, ui_event_Label19, LV_EVENT_ALL, NULL);






        // 创建开始/暂停按钮
        lv_obj_t* control_btn = lv_btn_create(lv_scr_act());
        lv_obj_set_size(control_btn, 20, 20);
        lv_obj_align(control_btn, LV_ALIGN_TOP_RIGHT, 190, -116);
        // 在按钮上添加标签
        lv_obj_t* control_label = lv_label_create(control_btn);

        // 创建重置按钮
        lv_obj_t* reset_btn = lv_btn_create(lv_scr_act());
        lv_obj_set_size(reset_btn, 20, 20);
        lv_obj_align(reset_btn, LV_ALIGN_TOP_RIGHT, 215, -116);
        // 在按钮上添加标签
        lv_obj_t* reset_label = lv_label_create(reset_btn);

        // 创建表格用于显示暂停时间
        lv_obj_t* table = lv_table_create(lv_scr_act());
        lv_obj_set_size(table, 420, 200);
        lv_obj_center(table);
        lv_table_set_row_cnt(table, 4); // 设置行数
        lv_table_set_col_cnt(table, 3); // 设置列数

        static bool clock_running = true; // 时钟运行状态标志
        static uint32_t start_time = 0; // 开始时间
        static uint32_t pause_time = 0; // 暂停时刻
        static uint32_t total_seconds = 0; // 总计秒数
        static uint8_t row_index = 0; // 表格行索引
        // 开始/暂停按钮点击事件回调函数
        void clock_control_event_cb(lv_event_t * e)
        {
            lv_obj_t* btn = lv_event_get_target(e); // 获取触发事件的对象
            if (clock_running) {
                pause_time = millis() - start_time;
                total_seconds = pause_time / 1000;
                clock_running = false;

                // 将暂停时间转换为秒数显示在表格第一行第三列
                char buffer[20];
                sprintf(buffer, "%lu", total_seconds);
                lv_table_set_cell_value_fmt(table, 1, 2, buffer);
                row_index++;
            }
            else {
                start_time = millis() - pause_time;
                clock_running = true;

            }
        }
        // 重置按钮点击事件回调函数
        void reset_clock_event_cb(lv_event_t * e)
        {
            clock_running = false;
            start_time = 0;
            pause_time = 0;
            total_seconds = 0;
            row_index = 0;
            // 清空表格内容
            for (int i = 0; i < 4; i++) {
                for (int j = 0; j < 3; j++) {
                    lv_table_set_cell_value(table, i, j, "");
                }
            }
            // 更新按钮文本为初始状态
            lv_label_set_text(lv_obj_get_child(control_btn, 0), "Pause");
        }

        // 将按钮点击事件与回调函数绑定
        lv_obj_add_event_cb(control_btn, clock_control_event_cb, LV_EVENT_CLICKED, NULL);
        lv_obj_add_event_cb(reset_btn, reset_clock_event_cb, LV_EVENT_CLICKED, NULL);

        // 示例：定时器更新时钟显示
        void update_clock(void)
        {
            static uint32_t last_time = 0;
            if (!clock_running) return; // 如果时钟处于暂停状态，则不更新
            uint32_t current_time = millis();
            if (current_time - last_time >= 1000) { // 每秒更新一次
                // 计算经过的时间
                uint32_t elapsed = current_time - start_time;
                uint32_t seconds = elapsed / 1000 % 60;
                uint32_t minutes = elapsed / 1000 / 60 % 60;
                uint32_t hours = elapsed / 1000 / 3600 % 24;
                // 格式化时间为HH:MM:SS格式
                char time_str[10];
                sprintf(time_str, "%02lu:%02lu:%02lu", hours, minutes, seconds);
                // 更新时钟显示逻辑
                lv_label_set_text(clock_label, time_str);
                last_time = current_time;
            }
        }



    }

    void ui_Screen2_screen_destroy(void)
    {
        if (ui_Screen2) lv_obj_del(ui_Screen2);

        // NULL screen variables
        ui_Screen2 = NULL;
        ui_Panel17 = NULL;
        ui_Label19 = NULL;
        ui_Label12 = NULL;
        ui_Panel7 = NULL;

    }


