// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project 1

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Panel10;
extern void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Keyboard4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

