// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project 1

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Keyboard4 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -102);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "智能胸带服务系统");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 389);
    lv_obj_set_height(ui_Panel5, 181);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, 25);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Panel5);
    lv_img_set_src(ui_Image3, &ui_img_01_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -118);
    lv_obj_set_y(ui_Image3, 5);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 60);

    ui_Label3 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 73);
    lv_obj_set_y(ui_Label3, -62);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "用户登录");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 39);
    lv_obj_set_height(ui_Button1, 19);
    lv_obj_set_x(ui_Button1, 138);
    lv_obj_set_y(ui_Button1, 93);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "确认");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 220);
    lv_obj_set_height(ui_Keyboard1, 75);
    lv_obj_set_x(ui_Keyboard1, 74);
    lv_obj_set_y(ui_Keyboard1, 103);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Panel10 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel10, 186);
    lv_obj_set_height(ui_Panel10, 86);
    lv_obj_set_x(ui_Panel10, 76);
    lv_obj_set_y(ui_Panel10, 29);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panel10, lv_color_hex(0x79A9FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_Panel10);
    lv_obj_set_width(ui_TextArea2, 108);
    lv_obj_set_height(ui_TextArea2, 30);
    lv_obj_set_x(ui_TextArea2, 29);
    lv_obj_set_y(ui_TextArea2, -21);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");

    ui_TextArea1 = lv_textarea_create(ui_Panel10);
    lv_obj_set_width(ui_TextArea1, 108);
    lv_obj_set_height(ui_TextArea1, 30);
    lv_obj_set_x(ui_TextArea1, 29);
    lv_obj_set_y(ui_TextArea1, 24);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_Panel3 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel3, 50);
    lv_obj_set_height(ui_Panel3, 30);
    lv_obj_set_x(ui_Panel3, -58);
    lv_obj_set_y(ui_Panel3, 24);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "密码");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font9, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel6, 50);
    lv_obj_set_height(ui_Panel6, 30);
    lv_obj_set_x(ui_Panel6, -58);
    lv_obj_set_y(ui_Panel6, -21);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "用户名");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard4 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard4, 220);
    lv_obj_set_height(ui_Keyboard4, 75);
    lv_obj_set_x(ui_Keyboard4, 75);
    lv_obj_set_y(ui_Keyboard4, 70);
    lv_obj_set_align(ui_Keyboard4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard4, ui_TextArea2);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label2 = NULL;
    ui_Panel5 = NULL;
    ui_Image3 = NULL;
    ui_Label3 = NULL;
    ui_Button1 = NULL;
    ui_Label7 = NULL;
    ui_Keyboard1 = NULL;
    ui_Panel10 = NULL;
    ui_TextArea2 = NULL;
    ui_TextArea1 = NULL;
    ui_Panel3 = NULL;
    ui_Label5 = NULL;
    ui_Panel6 = NULL;
    ui_Label4 = NULL;
    ui_Keyboard4 = NULL;

}
