// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project 1

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Panel7 = NULL;
// event funtions
void ui_event_Label19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel17 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel17, 480);
    lv_obj_set_height(ui_Panel17, 280);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -196);
    lv_obj_set_y(ui_Label19, -117);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "<<返回");
    lv_obj_add_flag(ui_Label19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_Label19, &ui_font_Font15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, -116);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "数据信息");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Font17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel7, 440);
    lv_obj_set_height(ui_Panel7, 215);
    lv_obj_set_x(ui_Panel7, 0);
    lv_obj_set_y(ui_Panel7, 14);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Label19, ui_event_Label19, LV_EVENT_ALL, NULL);

       lv_obj_t *table = lv_table_create(ui_Screen2);
       lv_obj_center(table);
       lv_obj_set_size(table, 420, 200);

       lv_table_set_cell_value(table, 0, 0, "Row 1, Col 1");
       lv_table_set_cell_value(table, 0, 1, "Row 1, Col 2");
       lv_table_set_cell_value(table, 0, 2, "Row 1, Col 3");
       lv_table_set_cell_value(table, 1, 0, "Xiao Hong");
       lv_table_set_cell_value(table, 1, 1, "108");   //
       lv_table_set_cell_value(table, 1, 2, "35");
       lv_table_set_cell_value(table, 2, 0, "Xiao Ming");
       lv_table_set_cell_value(table, 2, 1, "96");
       lv_table_set_cell_value(table, 2, 2, "35");

       const char *name1 = "Student";
       const char *name2 = "HR";
       const char *name3 = "Time";


       lv_table_set_cell_value_fmt(table, 0, 0, "%s", name1);
       lv_table_set_cell_value_fmt(table, 0, 1, "%s", name2);
       lv_table_set_cell_value_fmt(table, 0, 2, "%s", name3);

       lv_table_set_col_width(table, 0, 140);
       lv_table_set_col_width(table, 1, 140);
       lv_table_set_col_width(table, 2, 140);


}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Panel17 = NULL;
    ui_Label19 = NULL;
    ui_Label12 = NULL;
    ui_Panel7 = NULL;

}
