// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_Keyboard3 = NULL;
// event funtions
void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TextArea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -100);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "智能胸带服务系统");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 390);
    lv_obj_set_height(ui_Panel1, 180);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 14);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image1, &ui_img_01_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_Image1, -128);
    lv_obj_set_y(ui_Image1, -2);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 54);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 70);
    lv_obj_set_y(ui_Label2, -66);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "用户登录");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel2, 185);
    lv_obj_set_height(ui_Panel2, 90);
    lv_obj_set_x(ui_Panel2, 70);
    lv_obj_set_y(ui_Panel2, 0);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_Panel4, 50);
    lv_obj_set_height(ui_Panel4, 30);
    lv_obj_set_x(ui_Panel4, -55);
    lv_obj_set_y(ui_Panel4, -20);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "用户名");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_Panel5, 50);
    lv_obj_set_height(ui_Panel5, 30);
    lv_obj_set_x(ui_Panel5, -55);
    lv_obj_set_y(ui_Panel5, 20);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "密码");
    lv_obj_set_style_text_letter_space(ui_Label5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextArea2, 110);
    lv_obj_set_height(ui_TextArea2, 30);
    lv_obj_set_x(ui_TextArea2, 29);
    lv_obj_set_y(ui_TextArea2, -20);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");

    ui_TextArea3 = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextArea3, 110);
    lv_obj_set_height(ui_TextArea3, 30);
    lv_obj_set_x(ui_TextArea3, 29);
    lv_obj_set_y(ui_TextArea3, 20);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 40);
    lv_obj_set_height(ui_Button1, 20);
    lv_obj_set_x(ui_Button1, 147);
    lv_obj_set_y(ui_Button1, 80);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 147);
    lv_obj_set_y(ui_Label4, 80);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "确认");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard2, 286);
    lv_obj_set_height(ui_Keyboard2, 110);
    lv_obj_set_x(ui_Keyboard2, 86);
    lv_obj_set_y(ui_Keyboard2, 76);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Keyboard3 = lv_keyboard_create(ui_Screen1);
    lv_keyboard_set_mode(ui_Keyboard3, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard3, 286);
    lv_obj_set_height(ui_Keyboard3, 77);
    lv_obj_set_x(ui_Keyboard3, 86);
    lv_obj_set_y(ui_Keyboard3, 91);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextArea2);
    lv_keyboard_set_textarea(ui_Keyboard3, ui_TextArea3);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label1 = NULL;
    ui_Panel1 = NULL;
    ui_Image1 = NULL;
    ui_Label2 = NULL;
    ui_Panel2 = NULL;
    ui_Panel4 = NULL;
    ui_Label3 = NULL;
    ui_Panel5 = NULL;
    ui_Label5 = NULL;
    ui_TextArea2 = NULL;
    ui_TextArea3 = NULL;
    ui_Button1 = NULL;
    ui_Label4 = NULL;
    ui_Keyboard2 = NULL;
    ui_Keyboard3 = NULL;

}
