// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project
/*
#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions
void ui_event_Label6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -210);
    lv_obj_set_y(ui_Label6, -120);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "<<返回");
    lv_obj_add_flag(ui_Label6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -120);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "数据信息");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 120);
    lv_obj_set_y(ui_Label8, -70);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "00：00");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Font6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label6, ui_event_Label6, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;

}
*/


// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include <stdio.h>

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t* start_button = NULL;  // 新增全局变量
lv_obj_t* stop_button = NULL;
lv_timer_t* timer = NULL;
// event funtions

// build funtions


static void timer_callback(lv_timer_t* t) {
    lv_obj_t* label = (lv_obj_t*)t->user_data;
    if (ui_Label8 != NULL) {  // 确保标签有效
        static int seconds = 0;
        char buffer[20];
        sprintf(buffer, "Time: %d s", seconds++);
        lv_label_set_text(ui_Label8, buffer);
    }
}



void button_event_cb(lv_event_t* e)
{
    lv_obj_t* btn = lv_event_get_target(e);

    if (btn == start_button) {
        if (!timer) {
            timer = lv_timer_create(timer_callback, 1000, ui_Label8); // 每秒触发一次
        }
    }
    else if (btn == stop_button) {
        if (timer) {
            lv_timer_del(timer);
            timer = NULL;
        }
    }
}


void ui_Screen2_screen_init(void)
{
    if (timer) {
        lv_timer_del(timer);
        timer = NULL;
    }
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -210);
    lv_obj_set_y(ui_Label6, -120);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "<<返回");
    lv_obj_add_flag(ui_Label6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -120);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "数据信息");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 120);
    lv_obj_set_y(ui_Label8, -70);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "00：00");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Font6, LV_PART_MAIN | LV_STATE_DEFAULT);



    start_button = lv_btn_create(ui_Screen2);
    lv_obj_set_pos(start_button, 50, 100);
    lv_obj_set_size(start_button, 80, 40);
    lv_obj_set_style_bg_color(start_button, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); // 绿色按钮
    stop_button = lv_btn_create(ui_Screen2);
    lv_obj_set_pos(stop_button, 150, 100);
    lv_obj_set_size(stop_button, 80, 40);
    lv_obj_set_style_bg_color(stop_button, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // 红色按钮



    lv_obj_add_event_cb(start_button, button_event_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(stop_button, button_event_cb, LV_EVENT_CLICKED, NULL);





}






void ui_Screen2_screen_destroy(void)
{
    if (timer) {
        lv_timer_del(timer);
        timer = NULL;
    }
    if (ui_Screen2) lv_obj_del(ui_Screen2);

    ui_Screen2 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    start_button = NULL;
    stop_button = NULL;

    // 再删除对象

}







